:"2021-01-25T05:08:17.085Z","msg":"The New Relic collector rejected this agent.","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ip-172-31-42-57.us-east-2.compute.internal","pid":4643,"time"
:"2021-01-25T05:08:17.085Z","msg":"Agent state changed from connecting to errored."}
{"v":0,"level":50,"name":"newrelic","hostname":"ip-172-31-42-57.us-east-2.compute.internal","pid":4643,"time"
:"2021-01-25T05:08:17.086Z","msg":"New Relic for Node.js halted startup due to an error:","stack":"Error: Fai
led to connect to collector\n    at onStartConnect (/home/ec2-user/apps/battlestar/node_modules/newrelic/lib/
agent.js:236:18)\n    at retry (/home/ec2-user/apps/battlestar/node_modules/newrelic/lib/collector/api.js:115
:14)\n    at onPreConnect (/home/ec2-user/apps/battlestar/node_modules/newrelic/lib/collector/api.js:167:14)\
n    at Immediate._onImmediate (/home/ec2-user/apps/battlestar/node_modules/newrelic/lib/collector/parse-resp
onse.js:67:24)\n    at processImmediate (internal/timers.js:461:21)\n    at process.callbackTrampoline (inter
nal/async_hooks.js:126:14)","message":"Failed to connect to collector"}
{"v":0,"level":30,"name":"newrelic","hostname":"ip-172-31-42-57.us-east-2.compute.internal","pid":4671,"time"
:"2021-01-25T05:10:55.776Z","msg":"Using New Relic for Node.js. Agent version: 7.1.0; Node version: v12.20.1.
"}
{"v":0,"level":20,"name":"newrelic","hostname":"ip-172-31-42-57.us-east-2.compute.internal","pid":4671,"time"
:"2021-01-25T05:10:55.776Z","msg":"Loading agent from /home/ec2-user/apps/battlestar/node_modules/newrelic"}
{"v":0,"level":20,"name":"newrelic","hostname":"ip-172-31-42-57.us-east-2.compute.internal","pid":4671,"time"
:"2021-01-25T05:10:55.776Z","msg":"Process was running 0.033290484 seconds before agent was loaded."}
{"v":0,"level":20,"name":"newrelic","hostname":"ip-172-31-42-57.us-east-2.compute.internal","pid":4671,"time"
:"2021-01-25T05:10:55.780Z","msg":"Current working directory at module load is /home/ec2-user/apps/battlestar
."}

